# Generated by Django 5.1.6 on 2025-05-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_createlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='createlogin',
            old_name='surname',
            new_name='last_name',
        ),
    ]
